### ISSUE TITLE
Thread only FW for SkyConnect

### ISSUE THREAD

**Issue by mauimauer** [NabuCasa/silabs-firmware#6]
Would it be possible to add a firmware build with just Thread for use with OTBR for SkyConnect?

**Comment by agners** [comment]
Generally, yes. The problem is: Currently that is a one way street: There is no way to trigger the OpenThread RCP firmware to go back into bootloader mode. That means, once you've flashed the OpenThread RCP firmware, you'll not be able to flash something else, ever :sweat_smile: 

It would need firmware tweaking to allow a special OpenThread RCP command to send SkyConnect back into bootloader mode.

**Comment by Hedda** [comment]
FYI, for reference, I asked an indirectly related question in the Home Assistant forum, with a somewhat similar use case of only using my Home Assistant SkyConnect adapter as a dedicated Thread adapter, (because I already have a dedicated Texas Instruments CC2652P based  Zigbee Coordinator adapter for Home Assistant's ZHA integration and I would like to keep them on separate radios), however, I do not mind using RPC firmware on an adapter dedicated for Thread, but I just do not want the ZHA migration flow to be triggered automatically as I do not want to migrate, and I think I am probably not alone with that use case scenario -> https://community.home-assistant.io/t/home-assistant-skyconnect-usb-stick-announced-will-be-compatible-with-both-zigbee-and-thread-including-matter-chip-over-thread/433594/73

**Comment by MattWestb** [comment]
If one user like using one SkyConnect as only OTR RCP its only flashing it with multipan firmware and installing the addon and not using / enabling the network adapter for Zigbee and and using Z2M / ZHA with the other NCP connected to the system.

Perhaps putting in one option disable zigbeed can being good for the user case ?

**Comment by Hedda** [comment]
> The problem is: Currently that is a one way street: There is no way to trigger the OpenThread RCP firmware to go back into bootloader mode. That means, once you've flashed the OpenThread RCP firmware, you'll not be able to flash something else, ever 😅
> 
> It would need firmware tweaking to allow a special OpenThread RCP command to send SkyConnect back into bootloader mode.

@agners FYI, while not tested it myself it sounds as if Elelabs utility can use Spinel interface to restart adapter into bootloader?

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/blob/master/README.md#restart--restart-the-connected-generic-zigbeethread-product-in-normal-ezspspinel-mode-or-in-bootloader-mode

## restart – Restart the connected generic Zigbee/Thread product in Normal EZSP/Spinel mode or in Bootloader mode

> for any EZSP/Spinel product

The `restart` is used to probe the connected Zigbee/Thread product and restart it in normal or in bootloader mode. The normal mode is regular EZSP/Spinel operation. The bootloader mode is used only for the firmware update.

Switch from Normal mode to Bootloader mode

```
python3 Elelabs_EzspFwUtility.py restart -m btl -p /dev/ttyS6
```

![Elelabs Zigbee EZSP utility restart bootloader](/img/restart_btl.png?raw=true)

Switch from Bootloader mode to Normal mode

```
python3 Elelabs_EzspFwUtility.py restart -m nrml -p /dev/ttyS6
```

![Elelabs Zigbee EZSP utility restart normal](/img/restart_nrml.png?raw=true)

**Comment by agners** [comment]
@Hedda yes I am aware of Elelabs implementation, it uses a manufacturer specific command:
https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/blob/master/Elelabs_EzspFwUtility.py#L474-L477

The implementation on firmware side is not available, from what I know.

I tried to get Silicon Labs to implement a method long those lines in their official release, but so far that did not happen, unfortunately.

**Comment by agners** [comment]
Thread only firmware for SkyConnect is available now in [OpenThreadRCP](https://github.com/NabuCasa/silabs-firmware/tree/main/OpenThreadRCP). Once flashed, reflashing a newer firmware requires an universal-silabs-flasher which supports the OpenThread Spinel protocol and the reset into bootloader command. This is currently work in progress, see https://github.com/NabuCasa/universal-silabs-flasher/pull/13.
